version: "3.3"
services:
  continuum:
    build:
      context: .
      dockerfile: Dockerfile-continuum
      args:
        INSTALLER: ""
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "8080:8080"
      - "8083:8083"
  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: continuum
      MONGO_INITDB_ROOT_PASSWORD: continuum
volumes:
  mongodb-data: