version: "3.3"
services:
  continuum:
    build:
      context: .
      dockerfile: Dockerfile-continuum
      args:
        INSTALLER: ""
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "5000:8080"
#    command: >
#      /bin/bash -c "sleep 10
#      && source ~/.profile
#      && export CONTINUUM_HOME=/opt/continuum/current
#      && ctm-restart-services
#      && tail -f /var/continuum/log/ctm-ui.log"
  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: continuum
      MONGO_INITDB_ROOT_PASSWORD: continuum
volumes:
  mongodb-data: