version: "3.3"
services:

  continuum:
    build:
      args:
        INSTALLER: "https://s3.amazonaws.com/versionone-builds/continuum/installer/continuum-18.3.0.379-development-installer.sh"
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      CONTINUUM_ENCRYPTION_KEY: defaultkey
      CONTINUUM_MONGODB_SERVER: mongodb
      CONTINUUM_MONGODB_PORT: 27017
      CONTINUUM_MONGODB_NAME: continuum
      CONTINUUM_MONGODB_USERNAME: continuum
      CONTINUUM_MONGODB_PASSWORD: WC52OB8O/MniQ/JRxBrTbw==  # "continuum" encrypted with `defaultkey`
      CONTINUUM_MONGODB_AUTH: admin
    links:
      - mongodb
    ports:
      - "8080:8080"
      - "8083:8083"
    volumes:
      - ctm-logs:/var/continuum

  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: continuum
      MONGO_INITDB_ROOT_PASSWORD: continuum
    image: mongo:3.6-jessie
    volumes:
      - ctm-mongodb-data:/data/db

volumes:
  ctm-logs:
  ctm-mongodb-data:
