version: "3.3"
services:
  continuum:
    build:
      context: .
      dockerfile: Dockerfile-continuum
      args:
        INSTALLER: "https://s3.amazonaws.com/versionone-builds/continuum/installer/continuum-18.1.2.5-S-65321-mongo-support-envvars-installer.sh"
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "8080:8080"
      - "8083:8083"
    environment:
      CONTINUUM_MONGODB_SERVER: mongodb
      CONTINUUM_MONGODB_PORT: 27017
      CONTINUUM_MONGODB_NAME: continuum
#      CONTINUUM_MONGODB_USERNAME: continuum
#      CONTINUUM_MONGODB_PASSWORD: continuum
#      CONTINUUM_MONGODB_AUTH: continuum
    command: >
      /bin/bash -c "
        ctm-restart-services &&
        tail -f /var/continuum/log/ctm-ui.log
      "
  mongodb:
    image: mongo:3.6-jessie
    volumes:
      - mongodb-data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: continuum
#      MONGO_INITDB_ROOT_PASSWORD: continuum
volumes:
  mongodb-data:
