version: "3.7"
services:

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
      - proxy

  mail:
    image: namshi/smtp
    environment:
      DISABLE_IPV6: "true"
    restart: always
    ports:
      - "25:25"
    networks:
      - backend

  web:
    build:
      context: ..
      dockerfile: ./dev/Dockerfile
      target: web
    networks:
      - frontend
    ports:
      - "3000:3000"
    volumes:
      - $CONTINUUM_REPO:/app

  api:
    build:
      args:
        INSTALLER_LINK: ""
      context: ..
      dockerfile: ./dev/Dockerfile
      target: api
    depends_on:
      - mongodb
    env_file:
      - .env
    links:
      - mongodb
    networks:
      - proxy
      - frontend
      - backend
    expose:
      - "8080"
      - "8083"
    ports:
      - "8080:8080"
      - "8083:8083"
    volumes:
      - $CONTINUUM_REPO:/opt/continuum/current
      - $CONTINUUM_TOOLS:/opt/continuum/tools
      - ctm-dev-logs:/var/continuum
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mongodb:
    image: mongo:3.6-jessie
    logging:
      driver: "none"
    networks:
      - backend
    volumes:
      - ctm-dev-mongodb-data:/data/db

networks:
  frontend:
  backend:
  proxy:

volumes:
  ctm-dev-logs:
  ctm-dev-mongodb-data:
