version: "3.3"
services:

  continuum-frontend:
    build:
      context: ..
      dockerfile: ./dev/frontend.Dockerfile
    depends_on:
      - continuum-backend
    links:
      - continuum-backend
    ports:
      - "3000:3000"
    volumes:
      - $CONTINUUM_REPO:/app

  continuum-backend:
    build:
      args:
        INSTALLER: "https://s3.amazonaws.com/versionone-builds/continuum/installer/continuum-18.1.2.5-S-65321-mongo-support-envvars-installer.sh"
      context: ..
      dockerfile: ./dev/backend.Dockerfile
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      CONTINUUM_MONGODB_SERVER: mongodb
      CONTINUUM_MONGODB_PORT: 27017
      CONTINUUM_MONGODB_NAME: continuum
    links:
      - mongodb
    ports:
      - "9000:8080"
      - "8083:8083"
    volumes:
      - $CONTINUUM_REPO:/opt/continuum/current
      - ctm-dev-logs:/var/continuum

  mongodb:
    image: mongo:3.6-jessie
    volumes:
      - mongodb-data:/data/db

volumes:
  ctm-dev-logs:
  mongodb-data:
