version: "3.7"
services:

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock
    restart: always
    networks:
      - proxy

  smtp:
    image: namshi/smtp
    environment:
      DISABLE_IPV6: "true"
    restart: always
    ports:
      - "25:25"
    networks:
      - backend

  continuum:
    build:
      context: ..
      dockerfile: ./prod/Dockerfile
    environment:
      # Restarting services will attempt to create a new key and insert into the config.
      # Meaning authentication errors for data previous encrypted with older keys.
      CONTINUUM_ENCRYPTION_KEY: continuum
      CONTINUUM_MONGODB_SERVER: mongodb
      # Just to know that you can override the installer it used from here
      INSTALLER_LINK: ""
      VIRTUAL_HOST: continuum.prod.local
      VIRTUAL_PORT: 8080
      HTTPS_METHOD: noredirect
      HSTS: "off"
      # MSGHUB allows for wss connections
      UI_EXTERNAL_PORT: https://continuum.prod.local
      MSGUHB_EXTERNAL_PORT: wss://continuum.prod.local
    depends_on:
      - mongodb
    links:
      - mongodb
    expose:
      - "8080"
      - "8083"
    # Allows us to still reach localhost:8080
    ports:
      - "8080:8080"
      - "8083:8083"
    volumes:
      - logs:/var/continuum/log
    restart: always
    networks:
      - proxy
      - backend

  mongodb:
    image: mongo:3.6-jessie
    logging:
      driver: "none"
    volumes:
      - data:/data/db
    restart: always
    networks:
      - backend

volumes:
  logs:
  data:

networks:
  backend:
  proxy:
    external:
      name: proxy
