version: "3.7"
services:

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    restart: always
    networks:
      - prod

  continuum:
    build:
      context: ..
      dockerfile: ./prod/Dockerfile
    environment:
      CONTINUUM_MONGODB_SERVER: mongodb
      INSTALLER_LINK: ""
      VIRTUAL_HOST: local.prod.continuum
      VIRTUAL_PORT: 8080
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "8080:8080"
      - "8083:8083"
    volumes:
      - logs:/var/continuum/log
    restart: always
    networks:
      - prod

  mongodb:
    image: mongo:3.6-jessie
    logging:
      driver: "none"
    volumes:
      - data:/data/db
    restart: always
    networks:
      - prod

volumes:
  logs:
  data:

networks:
  prod:
