version: "3.7"
services:

  continuum:
    build:
      context: ..
      dockerfile: ./ossum/Dockerfile
    depends_on:
      - mongodb
    env_file:
      - .env
    links:
      - mongodb
    ports:
      - "8080:8080"
      - "8083:8083"
    volumes:
      - ossum-ctm-logs:/var/continuum/log

  mongodb:
    image: mongo:3.6-jessie
    logging:
      driver: "none"
    environment:
      MONGO_INITDB_ROOT_USERNAME: continuum
      MONGO_INITDB_ROOT_PASSWORD: continuum
    volumes:
      - ossum-ctm-data:/data/db

volumes:
  ossum-ctm-logs:
  ossum-ctm-data:
